ecom/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView

from users.views.reset_views import (UserPasswordChangeView,
                                     UserPasswordChangeDoneView,
                                     UserPasswordResetCompleteView,
                                     UserPasswordResetView,
                                     UserPasswordResetDoneView,
                                     UserPasswordResetConfirmView)


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    path('', RedirectView.as_view(url='/shop/')),

    path('accounts/', include('users.urls', namespace='users')),
    path('shop/', include('shop.urls', namespace="shop")),

    # Reset and Change
    path('password_change/', UserPasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', UserPasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset/', UserPasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),

    path('category/<int:category_id>/', views.get_category_detail, name="category"),

    path('products/', views.ShopView.as_view(), name="products"),
    path('product_detail/<int:product_id>/', views.get_product_details, name="product_detail"),
    path('product/<int:product_id>/add/', views.add_remove_product_quantity, {'op_type': 'add'}, name="add_product"),
    path('product/<int:product_id>/remove/', views.add_remove_product_quantity, {'op_type': 'remove'},
         name="remove_product"),

    path('product/<int:product_id>/add-to-cart/', views.add_to_cart, name="add_to_cart"),
    path('user/product-cart/', views.get_user_cart, name="user_cart"),

    path('user/cart/product/<int:ordered_item_id>/increase/', views.increase_product_quantity_in_cart,
         name="increase_product_in_cart"),
    path('user/cart/product/<int:ordered_item_id>/decrease/', views.decrease_product_quantity_in_cart,
         name="decrease_product_in_cart"),
    path('user/cart/product/<int:ordered_item_id>/remove/', views.remove_item_from_cart,
         name="remove_product_from_cart"),

    path('user/cart/checkout/', views.checkout, name="checkout"),
    path('user/cart/payment/', views.PaymentView.as_view(), name="payment"),

    path('contact-us/', views.ContactView.as_view(), name="contact_us"),
    path('about-us/', views.AboutView.as_view(), name="about_us"),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('signup/', views.SignUpView.as_view(), name="sign_up"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

users/models/users.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django_countries.fields import CountryField


class User(AbstractUser):
    GENDER = (
        ('F', 'Female'),
        ('M', 'Male')
    )

    USER_TYPE_CUSTOMER = 'CUSTOMER'
    USER_TYPE_ADMIN = 'ADMIN'
    USER_TYPE = (
        (USER_TYPE_ADMIN, 'admin'),
        (USER_TYPE_CUSTOMER, 'customer')
    )

    user_type = models.CharField(choices=USER_TYPE, max_length=20)
    gender = models.CharField(choices=GENDER, max_length=10)
    date_of_birth = models.DateField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    street_address = models.CharField(max_length=80, null=True, blank=True)
    country = CountryField()
    city = models.CharField(max_length=80)
    region_or_state = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

users/forms/login.py
import re

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label_suffix='', required=True, label="Username/Email",
                               help_text="Please enter your username or email address.",
                               widget=forms.TextInput(attrs={
                                   "id": "FormUsername",
                                   "name": "username",
                                   "class": "form-control"
                               }))
    password = forms.CharField(max_length=100, min_length=8, label_suffix='', required=True,
                               widget=forms.PasswordInput(attrs={
                                   "id": "FormPassword",
                                   "name": "password",
                                   "class": "form-control",
                                   "aria-describedby": "FormPasswordHelpBlock"}))

    def check_email(self):
        value = self.cleaned_data["username"]
        return re.match('^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$', value)

users/forms/profile.py
from django import forms

from django_countries.widgets import CountrySelectWidget

from users.models import User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'gender', 'date_of_birth',
                  'phone_number', 'street_address', 'country', 'city', 'region_or_state', )

        widgets = {
            'username': forms.TextInput(attrs={"class": "form-control"}),
            'first_name': forms.TextInput(attrs={"class": "form-control"}),
            'last_name': forms.TextInput(attrs={"class": "form-control"}),
            'email': forms.TextInput(attrs={"class": "form-control"}),
            'gender': forms.Select(attrs={"class": "form-control selectpicker"}),
            'date_of_birth': forms.DateTimeInput(attrs={"class": "form-control custom-datetimepicker"}),
            'phone_number': forms.TextInput(attrs={"class": "form-control"}),
            'street_address': forms.TextInput(attrs={"class": "form-control", "required": False}),
            'country': CountrySelectWidget(attrs={"class": "form-control selectpicker", "required": False}),
            'city': forms.TextInput(attrs={"class": "form-control", "required": False}),
            'region_or_state': forms.TextInput(attrs={"class": "form-control", "required": False}),
        }

users/forms/signup.py
from django import forms

from ..models import User


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=80, label="Username", label_suffix='', widget=forms.TextInput(attrs={
        "id": "SigUpFormUsername",
        "name": "username",
        "class": "form-control"}))
    first_name = forms.CharField(max_length=80, label_suffix='', widget=forms.TextInput(attrs={
        "id": "SignUpFormFirstName",
        "name": "first_name",
        "class": "form-control"
    }))
    last_name = forms.CharField(max_length=80, label_suffix='', widget=forms.TextInput(attrs={
        "id": "SignUpFormLastName",
        "name": "last_name",
        "class": "form-control"
    }))
    email = forms.EmailField(label_suffix='', widget=forms.EmailInput(attrs={
        "id": "FormEmail",
        "name": "email",
        "class": "form-control"
    }))
    password = forms.CharField(max_length=100, label_suffix='', min_length=8, required=True,
                               help_text='At least 8 characters and 1 digit',
                               widget=forms.PasswordInput(attrs={
                                   "id": "FormPassword",
                                   "class": "form-control",
                                   "aria-describedby": "FormPasswordHelpBlock"}))
    confirm_password = forms.CharField(max_length=100, label_suffix='', min_length=8, required=True,
                                       widget=forms.PasswordInput(attrs={
                                           "id": "FormPassword",
                                           "class": "form-control",
                                           "aria-describedby": "FormPasswordHelpBlock"}))
    phone_number = forms.CharField(max_length=15, label_suffix='', widget=forms.TextInput(attrs={
        "id": "FormPhone",
        "type": "tel",
        "class": "form-control",
        "aria-describedby": "FormPhoneHelpBlock"}))
    gender = forms.ChoiceField(choices=User.GENDER, label_suffix='', required=True, widget=forms.Select(attrs={
        "class": "form-control selectpicker",
        "id": "GenderSelect",
        "name": "gender",
    }))
    # user_type = forms.ChoiceField(choices=User.USER_TYPE, required=True, widget=forms.Select(attrs={
    #     "class": "form-control selectpicker",
    #     "id": "UserTypeSelect",
    #     "name": "user_type",
    # }))

    user_type = forms.CharField(widget=forms.HiddenInput(attrs={"value": User.USER_TYPE_CUSTOMER}))

    error_css_class = "text-danger"

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Account with such name already exists.")
        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Account with such email already exists.")
        return email

    def clean_confirm_password(self):
        password = self.cleaned_data["password"]
        confirm_password = self.cleaned_data["confirm_password"]

        if password != confirm_password:
            raise forms.ValidationError("Password not matched", code="password_match")
        return password

users/views/login_views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.models import Group

from ..models import User
from shop.models import Order

from ..forms import LoginForm, SignUpForm, UserProfileForm


def create_or_get_group(group_name):
    try:
        group = Group.objects.get(name=group_name)
    except Group.DoesNotExist:
        group = Group.objects.create(name=group_name)
    return group


class LoginView(View):
    template_name = 'users/login.html'
    context = {}

    def get(self, request, *args, **kwargs):
        self.context["form"] = LoginForm()
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)

        if form.is_valid():
            credential = {"password": form.cleaned_data["password"]}

            if form.check_email():
                credential["email"] = form.cleaned_data["username"]
            else:
                credential["username"] = form.cleaned_data["username"]

            user = authenticate(request, **credential)
            if user is not None:
                login(request, user)
                messages.success(request, "Welcome %s!" % user.get_full_name())
                return redirect('shop:home')
            else:
                messages.error(request, "Username and/or password does not exist")
                return redirect('users:login')

        self.context["form"] = form
        return render(request, self.template_name, self.context)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            logout(request)
            messages.success(request, 'You have successfully logged out!')
        return redirect('users:login')


class SignUpView(View):
    model = User
    template_name = 'users/sign_up.html'
    context = {}

    def get(self, request, *args, **kwargs):
        self.context["form"] = SignUpForm()
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data["username"],
                first_name=form.cleaned_data["first_name"],
                last_name=form.cleaned_data["last_name"],
                gender=form.cleaned_data["gender"],
                user_type=form.cleaned_data["user_type"],
                password=form.cleaned_data["confirm_password"],
                email=form.cleaned_data["email"],
                phone_number=form.cleaned_data["phone_number"]
            )

            user.groups.add(create_or_get_group(user.user_type))

            user = authenticate(request,
                                username=form.cleaned_data["username"],
                                password=form.cleaned_data["confirm_password"])
            login(request, user)
            # redirect to profile view
            messages.success(self.request, "Sign up successful")
            return redirect('shop:home')

        self.context["form"] = form
        return render(request, self.template_name, self.context)


class UserProfileView(LoginRequiredMixin, View):
    model = User
    template_name = 'users/profile.html'
    context = {}

    def get(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except User.DoesNotExist:
            return redirect('users:sign_up')

        self.context['form'] = UserProfileForm(instance=user)
        self.context['user_order'] = Order.get_user_pending_order(request.user),
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(id=request.user.id)
        except User.DoesNotExist:
            return redirect('users:sign_up')

        form = UserProfileForm(request.POST, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully")
        else:
            messages.error(request, "Updating profile failed")
        return redirect('users:profile')

users/views/reset_views.py
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetCompleteView)


class UserPasswordResetView(PasswordResetView):
    template_name = 'users/reset/password_reset_form.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/reset/password_reset_confirm.html'


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/reset/password_reset_done.html'


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/reset/password_reset_complete.html'


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'users/reset/password_change_form.html'


class UserPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'users/reset/password_change_done.html'

users/templates/footer.html
{% load static %}

<footer class="site-footer border-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Contact</a></li>
                  <li><a href="#">Private Policy</a></li>
                  <li><a href="#">T & Cs</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Login / Register</a></li>
                  <li><a href="#">Shopping Cart</a></li>
                  <li><a href="#">Checkout</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Point of sale</a></li>
                  <li><a href="#">Hardware</a></li>
                  <li><a href="#">Software</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            <h3 class="footer-heading mb-4">Promo</h3>
            <a href="#" class="block-6">
              <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded mb-4">
              <h3 class="font-weight-light  mb-0">Finding Your Perfect Shoes</h3>
              <p>Promo from  nuary 15 &mdash; 25, 2019</p>
            </a>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">203 Fake St. Mountain View, Acrra, Ghana</li>
                <li class="phone"><a href="tel://23923929210">+2 332 3929 210</a></li>
                <li class="email">emailaddress@domain.com</li>
              </ul>
            </div>

            <div class="block-7">
              <form action="#" method="post">
                <label for="email_subscribe" class="footer-heading">Subscribe</label>
                <div class="form-group">
                  <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                  <input type="submit" class="btn btn-sm btn-primary" value="Send">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
            </p>
          </div>

        </div>
      </div>
   </footer>

users/templates/site_navbar.html
<div class="site-navbar-top">
    <div class="container">
        <div class="row align-items-center">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                <form action="" class="site-block-top-search">
                    <span class="icon icon-search2"></span>
                    <input type="text" class="form-control border-0" placeholder="Search">
                </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div class="site-logo">
                <a href="/shop" class="js-logo-clone">Market</a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons">
                <ul>
                  {% if request.user.is_authenticated %}
                  <li class="dropdown">
                    <a href="#" class="badge badge-pill badge-light border d-inline-flex dropdown-toggle"
                       data-toggle="dropdown" id="userAccount" aria-haspopup="true" aria-expanded="false">
                      <span class="icon icon-person"></span>
                      <span class="font-weight-light ml-1" style="line-height: 21px;font-size: 12px;">{{user.get_full_name|title}}</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="userAccount">
                      <a class="dropdown-item text-muted" style="font-size:13px;" href="{% url 'users:logout' %}">Logout</a>
                      <a class="dropdown-item text-muted" style="font-size:13px;" href="{% url 'users:profile' %}">Update Profile</a>
                      <a class="dropdown-item text-muted" style="font-size:13px;" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                  </li>
                  {% else %}
                  <li>
                    <div class="btn-group btn-group-sm rounded-circle" role="group">
                      <a href="{% url 'users:login' %}" class="btn btn-light text-dark">Sign in</a>
                      <a href="{% url 'users:sign_up' %}" class="btn btn-info text-dark">Sign up</a>
                    </div>
                  </li>
                  {% endif %}
                  <li>
                    <a href="{% url 'shop:user_cart' %}" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                      <span class="count">{% if user_order %}{{user_order.items.all|length}}{% else %}0{% endif %}</span>
                    </a>
                  </li>
                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                </ul>
              </div>
            </div>

        </div>
    </div>
</div>

users/templates/site_navigation.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block">
            <li class="has-children active">
                <a href="{% url 'shop:home' %}">Home</a>
                <ul class="dropdown">
                    {% for category in categories %}
                    <li>
                        <a href="{% url 'shop:category' category_id=category.id %}">
                            <span>{{category.name|title}}</span>
                            <!--span class="text-black ml-auto">(2,220)</span-->
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="has-children">
                <a href="{% url 'shop:about_us' %}">About</a>
                <ul class="dropdown">
                    <li><a href="{% url 'shop:about_us' %}">About Us</a></li>
                </ul>
            </li>
            <li><a href="{% url 'shop:products' %}">Shop</a></li>
            <!--li><a href="#">Catalogue</a></li-->
            <!--li><a href="#">New Arrivals</a></li-->
            <li><a href="{% url 'shop:contact_us' %}">Contact</a></li>
        </ul>
    </div>
</nav>