ecom/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView

from users.views.reset_views import (UserPasswordChangeView,
                                     UserPasswordChangeDoneView,
                                     UserPasswordResetCompleteView,
                                     UserPasswordResetView,
                                     UserPasswordResetDoneView,
                                     UserPasswordResetConfirmView)


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    path('', RedirectView.as_view(url='/shop/')),

    path('accounts/', include('users.urls', namespace='users')),
    path('shop/', include('shop.urls', namespace="shop")),

    # Reset and Change
    path('password_change/', UserPasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', UserPasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset/', UserPasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),

    path('category/<int:category_id>/', views.get_category_detail, name="category"),

    path('products/', views.ShopView.as_view(), name="products"),
    path('product_detail/<int:product_id>/', views.get_product_details, name="product_detail"),
    path('product/<int:product_id>/add/', views.add_remove_product_quantity, {'op_type': 'add'}, name="add_product"),
    path('product/<int:product_id>/remove/', views.add_remove_product_quantity, {'op_type': 'remove'},
         name="remove_product"),

    path('product/<int:product_id>/add-to-cart/', views.add_to_cart, name="add_to_cart"),
    path('user/product-cart/', views.get_user_cart, name="user_cart"),

    path('user/cart/product/<int:ordered_item_id>/increase/', views.increase_product_quantity_in_cart,
         name="increase_product_in_cart"),
    path('user/cart/product/<int:ordered_item_id>/decrease/', views.decrease_product_quantity_in_cart,
         name="decrease_product_in_cart"),
    path('user/cart/product/<int:ordered_item_id>/remove/', views.remove_item_from_cart,
         name="remove_product_from_cart"),

    path('user/cart/checkout/', views.checkout, name="checkout"),
    path('user/cart/payment/', views.PaymentView.as_view(), name="payment"),

    path('contact-us/', views.ContactView.as_view(), name="contact_us"),
    path('about-us/', views.AboutView.as_view(), name="about_us"),
]

shop/models/coupon.py
from django.db import models


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

shop/models/payment.py
from django.db import models

from users.models import User


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

shop/forms/checkout.py
from django import forms

from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


# PAYMENT_CHOICES = (
#     ('MTN_MOBILE_MONEY', 'mtn mobile money'),
#     ('PAYPAL', 'paypal'),
# )


class CheckOutForm(forms.Form):
    shipping_address = forms.CharField(required=False,
                                       widget=forms.TextInput(attrs={
                                           'id': "c_shipping_address",
                                           "class": "form-control", "placeholder": "Street address"})
                                       )
    shipping_address2 = forms.CharField(required=False,
                                        widget=forms.TextInput(attrs={
                                            'id': 'o_shipping_address',
                                            "class": "form-control",
                                            "placeholder": "Apartment, suite, unit etc. (optional)"})
                                        )
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'id': "shipping_country",
            'class': 'form-control selectpicker',
        }))
    shipping_zip = forms.CharField(required=False)
    shipping_region = forms.CharField(required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    shipping_user_email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))
    shipping_user_phone_number = forms.CharField(max_length=15, widget=forms.TextInput(attrs={"class": "form-control"}))

    billing_address = forms.CharField(required=False,
                                      widget=forms.TextInput(attrs={
                                          'id': "c_billing_address",
                                          "class": "form-control",
                                          "placeholder": "Street address"})
                                      )
    billing_address2 = forms.CharField(required=False,
                                       widget=forms.TextInput(attrs={
                                           'id': 'o_billing_address',
                                           "class": "form-control",
                                           "placeholder": "Apartment, suite, unit etc. (optional)"})
                                       )
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'id': "billing_country",
            'class': 'form-control selectpicker',
        }))
    billing_zip = forms.CharField(required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    billing_region = forms.CharField(required=False, widget=forms.TextInput(attrs={"class": "form-control"}))
    billing_user_email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))
    billing_user_phone_number = forms.CharField(max_length=15, widget=forms.TextInput(attrs={"class": "form-control"}))

    use_different_shipping_address = forms.BooleanField(required=False)

    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)

    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)
    
    order_notes = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control",
                                                               "cols": "30", "rows": "4",
                                                               "placeholder": "Write your notes here..."}),
                                  required=False)

    # payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

shop/views/checkout.py
from django.shortcuts import render, redirect
from django.contrib import messages
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
# from django.utils import timezone

from ..models import Order, ItemCategory, OrderedItem, Address

from ..forms.checkout import CheckOutForm


def set_shipping_address_fields(form, shipping_address):
    form.fields['shipping_country'].initial = shipping_address.country
    form.fields['shipping_address'].initial = shipping_address.street_address
    form.fields['shipping_address2'].initial = shipping_address.apartment_address
    form.fields['shipping_region'].initial = shipping_address.region_or_state
    form.fields['shipping_zip'].initial = shipping_address.zip
    form.fields['shipping_user_email'].initial = shipping_address.email
    form.fields['shipping_user_phone_number'].initial = shipping_address.phone_number
    return form


def set_billing_address_fields(form, billing_address):
    form.fields['billing_country'].initial = billing_address.country
    form.fields['billing_address'].initial = billing_address.street_address
    form.fields['billing_address2'].initial = billing_address.apartment_address
    form.fields['billing_region'].initial = billing_address.region_or_state
    form.fields['billing_zip'].initial = billing_address.zip
    form.fields['billing_user_email'].initial = billing_address.email
    form.fields['billing_user_phone_number'].initial = billing_address.phone_number
    return form


@login_required()
def checkout(request):
    template_name = "shop/checkout.html"

    if request.method == "GET":
        shipping_address = billing_address = None
        form = CheckOutForm()

        user_pending_order = Order.get_user_pending_order(user=request.user)

        if user_pending_order is None:
            messages.warning(request, "Sorry you have no pending order")
            return redirect('shop:products')

        if user_pending_order.shipping_address and \
                user_pending_order.billing_address:
            form = set_billing_address_fields(form, user_pending_order.billing_address)
            form = set_shipping_address_fields(form, user_pending_order.shipping_address)
        else:
            shipping_address_qs = Address.objects.filter(user=request.user, default=True,
                                                         address_type=Address.SHIPPING_ADDRESS)
            if shipping_address_qs.exists():
                shipping_address = shipping_address_qs[0]
                form = set_shipping_address_fields(form, shipping_address)

            billing_address_qs = Address.objects.filter(user=request.user, default=True,
                                                        address_type=Address.BILLING_ADDRESS)
            if billing_address_qs.exists():
                billing_address = billing_address_qs[0]
                form = set_billing_address_fields(form, billing_address)

        context = {
            "categories": ItemCategory.objects.all(),
            'user_order': Order.get_user_pending_order(request.user),
            "form": form,
            "shipping_address": shipping_address,
            "billing_address": billing_address
        }

        return render(request, template_name, context=context)

    elif request.method == "POST":
        form = CheckOutForm(request.POST or None)

        if form.is_valid():
            user_pending_order = Order.get_user_pending_order(user=request.user)

            if user_pending_order is None:
                messages.warning(request, "Sorry you have no pending order")
                return redirect('shop:products')

            use_different_shipping_address = form.cleaned_data.get('use_different_shipping_address')

            billing_address_qs = Address.objects.filter(user=request.user,
                                                        address_type=Address.BILLING_ADDRESS,
                                                        country=form.cleaned_data.get('billing_country'),
                                                        street_address=form.cleaned_data.get('billing_address'),
                                                        apartment_address=form.cleaned_data.get('billing_address2'),
                                                        region_or_state=form.cleaned_data.get('billing_region'),
                                                        zip=form.cleaned_data.get('billing_zip'),
                                                        email=form.cleaned_data.get('billing_user_email'),
                                                        phone_number=form.cleaned_data.get('billing_user_phone_number'))
            if billing_address_qs.exists():
                billing_address = billing_address_qs[0]
            else:
                billing_address = Address.objects.create(user=request.user,
                                                         address_type=Address.BILLING_ADDRESS,
                                                         country=form.cleaned_data.get('billing_country'),
                                                         street_address=form.cleaned_data.get('billing_address'),
                                                         apartment_address=form.cleaned_data.get('billing_address2'),
                                                         region_or_state=form.cleaned_data.get('billing_region'),
                                                         zip=form.cleaned_data.get('billing_zip'),
                                                         email=form.cleaned_data.get('billing_user_email'),
                                                         phone_number=form.cleaned_data.get('billing_user_phone_number'))

            if not use_different_shipping_address:  # == 'off':
                shipping_address_qs = Address.objects.filter(user=request.user,
                                                             address_type=Address.SHIPPING_ADDRESS,
                                                             country=form.cleaned_data.get('shipping_country'),
                                                             street_address=form.cleaned_data.get('shipping_address'),
                                                             apartment_address=form.cleaned_data.get('shipping_address2'),
                                                             region_or_state=form.cleaned_data.get('shipping_region'),
                                                             zip=form.cleaned_data.get('shipping_zip'),
                                                             email=form.cleaned_data.get('shipping_user_email'),
                                                             phone_number=form.cleaned_data.get(
                                                                 'shipping_user_phone_number'))
                if shipping_address_qs.exists():
                    shipping_address = shipping_address_qs[0]
                else:
                    shipping_address = Address.objects.create(user=request.user,
                                                              address_type=Address.SHIPPING_ADDRESS,
                                                              country=form.cleaned_data.get('shipping_country'),
                                                              street_address=form.cleaned_data.get('shipping_address'),
                                                              apartment_address=form.cleaned_data.get('shipping_address2'),
                                                              region_or_state=form.cleaned_data.get('shipping_region'),
                                                              zip=form.cleaned_data.get('shipping_zip'),
                                                              email=form.cleaned_data.get('shipping_user_email'),
                                                              phone_number=form.cleaned_data.get(
                                                                  'shipping_user_phone_number'))
            else:
                shipping_address = billing_address

            user_pending_order.shipping_address = shipping_address
            user_pending_order.billing_address = billing_address
            user_pending_order.save()

        return redirect('shop:payment')

shop/views/home.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View

from ..models import ItemCategory, Order


class HomePage(View):
    template_name = 'shop/home.html'
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "categories": ItemCategory.objects.all(),
            'user_order': Order.get_user_pending_order(request.user),
        }
        return render(request, self.template_name, self.context)

shop/views/order.py
from django.shortcuts import render
from django.contrib import messages
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils import timezone

from ..models import Order, ItemCategory, OrderedItem


def get_user_cart(request):
    template_name = 'shop/cart.html'

    if request.method == 'GET':
        previous_url = request.META.get('HTTP_REFERER')

        user_order = Order.get_user_pending_order(request.user)
        if not user_order:
            messages.error(request, "You have no item in your cart.")
            return redirect(previous_url)

        context = {
            "categories": ItemCategory.objects.all(),
            'user_order': Order.get_user_pending_order(request.user),
        }
        return render(request, template_name, context)


# @login_required()
# def inc_dec_product_in_cart(request, ordered_item_id, op_type="increase"):
#     if request.method == "GET":
#         try:
#             item = OrderedItem.objects.get(id=ordered_item_id)
#         except OrderedItem.DoesNotExist:
#             return redirect('shop:home')

shop/templates/shop/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'shop:home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <a href="{% url 'shop:user_cart' %}">Cart</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Checkout</strong></div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <form method="post" action="">
            {% csrf_token %}
        <div class="row">
            <div class="col-md-6 mb-5 mb-md-0">
                <h2 class="h3 mb-3 text-black">Billing Details</h2>
                <div class="p-3 p-lg-5 border">
                    <div class="form-group">
                        <label for="billing_country" class="text-black">Country <span class="text-danger">*</span></label>
                        {{form.billing_country}}
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="c_billing_address" class="text-black">Address <span class="text-danger">*</span></label>
                            {{form.billing_address}}
                        </div>
                    </div>
                    <div class="form-group">
                        {{form.billing_address2}}
                    </div>

                  <div class="form-group row">
                    <div class="col-md-6">
                      <label for="id_billing_region" class="text-black">State / County / Region <span class="text-danger">*</span></label>
                      {{form.billing_region}}
                    </div>
                    <div class="col-md-6">
                      <label for="id_billing_zip" class="text-black">Postal / Zip <span class="text-danger">*</span></label>
                      {{form.billing_zip}}
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-md-6">
                      <label for="id_billing_user_email" class="text-black">Email Address <span class="text-danger">*</span></label>
                        {% if billing_address is None %}
                      <input type="email" class="form-control" id="id_billing_user_email" placeholder="Email"
                             name="{{form.billing_user_email.name}}" value={{user.email}}>
                        {% else %}
                        {{form.billing_user_email}}
                        {% endif %}
                    </div>
                    <div class="col-md-6">
                      <label for="id_billing_user_phone_number" class="text-black">Phone <span class="text-danger">*</span></label>
                        {% if billing_address is None %}
                      <input type="text" class="form-control" id="id_billing_user_phone_number" name="{{form.billing_user_phone_number.name}}"
                             value="{{user.phone_number}}" placeholder="Phone Number" maxlength="15">
                        {% else %}
                        {{form.billing_user_phone_number}}
                        {% endif %}
                    </div>
                  </div>

                  <div class="form-group row mb-5">
                      <div class="col">
                          {{form.set_default_billing}} <label class="text-black">Set as the default billing address.</label>
                      </div>
                  </div>

                  <div class="form-group">
                    <label for="id_use_different_shipping_address" class="text-black" data-toggle="collapse"
                           href="#ship_different_address" role="button" aria-expanded="false" aria-controls="ship_different_address">
                      {{form.use_different_shipping_address}} Ship To A Different Address?
                    </label>
                    <div class="collapse" id="ship_different_address">
                      <div class="py-2">
                        <div class="form-group">
                          <label for="shipping_country" class="text-black">Country <span class="text-danger">*</span></label>
                          {{form.shipping_country}}
                        </div>

                        <div class="form-group row">
                          <div class="col-md-12">
                            <label for="c_shipping_address" class="text-black">Address <span class="text-danger">*</span></label>
                            {{form.shipping_address}}
                          </div>
                        </div>

                        <div class="form-group">
                          {{form.shipping_address2}}
                        </div>

                        <div class="form-group row">
                          <div class="col-md-6">
                            <label for="id_shipping_region" class="text-black">State / County / Region <span class="text-danger">*</span></label>
                            {{form.shipping_region}}
                          </div>
                          <div class="col-md-6">
                            <label for="id_shipping_zip" class="text-black">Postal / Zip <span class="text-danger">*</span></label>
                            {{form.shipping_zip}}
                          </div>
                        </div>

                        <div class="form-group row">
                          <div class="col-md-6">
                            <label for="id_shipping_user_email" class="text-black">Email Address <span class="text-danger">*</span></label>
                              {% if shipping_address is None %}
                            <input type="email" class="form-control" id="id_shipping_user_email" name="{{form.shipping_user_email.name}}"
                                   value="{{user.email}}">
                              {% else %}
                              {{form.shipping_user_email}}
                              {% endif %}
                          </div>
                          <div class="col-md-6">
                            <label for="id_shipping_user_phone_number" class="text-black">Phone <span class="text-danger">*</span></label>
                              {% if shipping_address is None %}
                            <input type="text" class="form-control" id="id_shipping_user_phone_number" value="{{user.phone_number}}"
                                   name="{{form.shipping_user_phone_number.name}}" maxlength="15" placeholder="Phone Number">
                              {% else %}
                              {{form.shipping_user_phone_number}}
                              {% endif %}
                          </div>
                        </div>

                          <div class="form-group row mb-5">
                              <div class="col">
                                  {{form.set_default_shipping}} <label class="text-black">Set as the default shipping address.</label>
                              </div>
                          </div>

                      </div>

                    </div>
                  </div>

                  <div class="form-group">
                      <label for="id_order_notes" class="text-black">Order Notes</label>
                      {{form.order_notes}}
                  </div>

                </div>
            </div>

          <div class="col-md-6">

            <div class="row mb-5">
              <div class="col-md-12">
                <h2 class="h3 mb-3 text-black">Your Order</h2>
                <div class="p-3 p-lg-5 border">
                  <table class="table table-hover site-block-order-table mb-5">
                    <thead>
                    <th>Product</th>
                    <th>Total</th>
                    </thead>
                    <tbody>
                    {% for product in user_order.items.all %}
                    <tr>
                      <td>{{product.item.title|title}} <strong class="mx-2">x</strong> {{product.quantity}}</td>
                      <td>$250.00</td>
                    </tr>
                    {% endfor %}
                    <tr>
                      <td class="text-black font-weight-bold"><strong>Cart Subtotal</strong></td>
                      <td class="text-black">${{user_order.get_sub_total}}</td>
                    </tr>
                    <tr>
                      <td class="text-black font-weight-bold"><strong>Coupon</strong></td>
                      <td class="text-success">-$0.00</td>
                    </tr>
                    <tr class="bg-success">
                      <td class="text-black font-weight-bold"><strong>Order Total</strong></td>
                      <td class="text-black font-weight-bold"><strong>${{user_order.get_total}}</strong></td>
                    </tr>
                    </tbody>
                  </table>

                  <!--{% for value, name in form.fields.payment_option.choices %}-->
                  <!--<div class="border p-3 mb-3">-->
                    <!--<h4 class="h5 mb-0 d-inline-flex">-->
                      <!--<input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="" required>-->
                      <!--<a class="d-block ml-2" data-toggle="collapse" href="#collapse-{{value}}" role="button"-->
                         <!--aria-expanded="false" aria-controls="collapse-{{value}}">{{ name|title }}</a>-->
                    <!--</h4>-->

                    <!--<div class="collapse" id="collapse-{{value}}">-->
                      <!--<div class="py-2">-->
                        <!--<p class="mb-0">-->
                          <!--Make your payment directly into our bank account. Please use your Order ID as the payment reference.-->
                          <!--Your order won’t be shipped until the funds have cleared in our account.-->
                        <!--</p>-->
                      <!--</div>-->
                    <!--</div>-->
                  <!--</div>-->
                  <!--{% endfor %}-->

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg py-3 btn-block">Place Order</button>
                  </div>

                </div>
              </div>
            </div>

          </div>
        </div>
        </form>
      </div>
    </div>
{% endblock content %}

shop/templates/shop/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="{% url 'shop:home' %}">Home</a>
              <span class="mx-2 mb-0">/</span> <strong class="text-black">Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2 class="h3 mb-3 text-black">Get In Touch</h2>
          </div>
          <div class="col-md-7">

            <form action="#" method="post">

              <div class="p-3 p-lg-5 border">
                <div class="form-group row">
                  <div class="col-md-6">
                    <label for="c_fname" class="text-black">First Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="c_fname" name="c_fname">
                  </div>
                  <div class="col-md-6">
                    <label for="c_lname" class="text-black">Last Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="c_lname" name="c_lname">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_email" class="text-black">Email <span class="text-danger">*</span></label>
                    <input type="email" class="form-control" id="c_email" name="c_email" placeholder="">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_subject" class="text-black">Subject </label>
                    <input type="text" class="form-control" id="c_subject" name="c_subject">
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_message" class="text-black">Message </label>
                    <textarea name="c_message" id="c_message" cols="30" rows="7" class="form-control"></textarea>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-lg-12">
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Send Message">
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="col-md-5 ml-auto">
            <div class="p-4 border mb-3">
              <span class="d-block text-primary h6 text-uppercase">Accra</span>
              <p class="mb-0">203 Fake St. Mountain View, Dzorwulu, Accra, Ghana</p>
            </div>

          </div>
        </div>
      </div>
    </div>
{% endblock content %}